package com.citidev.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ReceiptDTO {

    // ====== Column Name Constants ======
    public static final String COLUMNNAME_Id = "Id";
    public static final String COLUMNNAME_Name = "Name";
    public static final String COLUMNNAME_Account = "Account__c";
    public static final String COLUMNNAME_Amount = "Amount__c";
    public static final String COLUMNNAME_Autogenerated = "Autogenerated__c";
    public static final String COLUMNNAME_Bank = "Bank__c";
    public static final String COLUMNNAME_Customer_Bank = "CustomerBank__c";
    public static final String COLUMNNAME_DueDate = "DueDate__c";
    public static final String COLUMNNAME_Opportunity = "Opportunity__c";
    public static final String COLUMNNAME_PaymentReference = "PaymentReference__c";
    public static final String COLUMNNAME_PaymentStatus = "PaymentStatus__c";
    public static final String COLUMNNAME_Payment_Method = "Payment_Method__c";
    public static final String COLUMNNAME_Payment = "Payment__c";
    public static final String COLUMNNAME_Project = "Project__c";
    public static final String COLUMNNAME_ReceiptDate = "ReceiptDate__c";
    public static final String COLUMNNAME_SFUniqueNumber = "SFUniqueNumber__c";
    public static final String COLUMNNAME_Status = "Status__c";
    public static final String COLUMNNAME_Unit = "Unit__c";
    public static final String COLUMNNAME_Record_Id = "Record_Id__c";
    public static final String COLUMNNAME_LastModifiedDate = "LastModifiedDate";
    

    // ====== Fields ======
    @JsonProperty(COLUMNNAME_Id)
    private String Id;

    @JsonProperty(COLUMNNAME_Name)
    private String Name;

    @JsonProperty(COLUMNNAME_Account)
    private String Account__c;

    @JsonProperty(COLUMNNAME_Amount)
    private String Amount__c;

    @JsonProperty(COLUMNNAME_Autogenerated)
    private boolean Autogenerated__c;

    @JsonProperty(COLUMNNAME_Bank)
    private String Bank__c;

    @JsonProperty(COLUMNNAME_Customer_Bank)
    private String CustomerBank__c;

    @JsonProperty(COLUMNNAME_DueDate)
    private String DueDate__c;

    @JsonProperty(COLUMNNAME_Opportunity)
    private String Opportunity__c;

    @JsonProperty(COLUMNNAME_PaymentReference)
    private String PaymentReference__c;

    @JsonProperty(COLUMNNAME_PaymentStatus)
    private String PaymentStatus__c;

    @JsonProperty(COLUMNNAME_Payment_Method)
    private String Payment_Method__c;

    @JsonProperty(COLUMNNAME_Payment)
    private String Payment__c;

    @JsonProperty(COLUMNNAME_Project)
    private String Project__c;

    @JsonProperty(COLUMNNAME_ReceiptDate)
    private String ReceiptDate__c;

    @JsonProperty(COLUMNNAME_SFUniqueNumber)
    private String SFUniqueNumber__c;

    @JsonProperty(COLUMNNAME_Status)
    private String Status__c;

    @JsonProperty(COLUMNNAME_Unit)
    private String Unit__c;

    @JsonProperty(COLUMNNAME_Record_Id)
    private String Record_Id__c;

    @JsonProperty(COLUMNNAME_LastModifiedDate)
    private String LastModifiedDate;

    // ====== Getters and Setters ======

    public String getId() {
        return Id;
    }

    public void setId(String id) {
        this.Id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        this.Name = name;
    }

    public String getAccount__c() {
        return Account__c;
    }

    public void setAccount__c(String account__c) {
        this.Account__c = account__c;
    }

    public String getAmount__c() {
        return Amount__c;
    }

    public void setAmount__c(String amount__c) {
        this.Amount__c = amount__c;
    }

    public boolean isAutogenerated__c() {
        return Autogenerated__c;
    }

    public void setAutogenerated__c(boolean autogenerated__c) {
        this.Autogenerated__c = autogenerated__c;
    }

    public String getBank__c() {
        return Bank__c;
    }

    public void setBank__c(String bank__c) {
        this.Bank__c = bank__c;
    }

    public String getCustomerBank__c() {
        return CustomerBank__c;
    }

    public void setCustomerBank__c(String customerBank__c) {
        this.CustomerBank__c = customerBank__c;
    }

    public String getDueDate__c() {
        return DueDate__c;
    }

    public void setDueDate__c(String dueDate__c) {
        this.DueDate__c = dueDate__c;
    }

    public String getOpportunity__c() {
        return Opportunity__c;
    }

    public void setOpportunity__c(String opportunity__c) {
        this.Opportunity__c = opportunity__c;
    }

    public String getPaymentReference__c() {
        return PaymentReference__c;
    }

    public void setPaymentReference__c(String paymentReference__c) {
        this.PaymentReference__c = paymentReference__c;
    }

    public String getPaymentStatus__c() {
        return PaymentStatus__c;
    }

    public void setPaymentStatus__c(String paymentStatus__c) {
        this.PaymentStatus__c = paymentStatus__c;
    }

    public String getPayment_Method__c() {
        return Payment_Method__c;
    }

    public void setPayment_Method__c(String payment_Method__c) {
        this.Payment_Method__c = payment_Method__c;
    }

    public String getPayment__c() {
        return Payment__c;
    }

    public void setPayment__c(String payment__c) {
        this.Payment__c = payment__c;
    }

    public String getProject__c() {
        return Project__c;
    }

    public void setProject__c(String project__c) {
        this.Project__c = project__c;
    }

    public String getReceiptDate__c() {
        return ReceiptDate__c;
    }

    public void setReceiptDate__c(String receiptDate__c) {
        this.ReceiptDate__c = receiptDate__c;
    }

    public String getSFUniqueNumber__c() {
        return SFUniqueNumber__c;
    }

    public void setSFUniqueNumber__c(String sFUniqueNumber__c) {
        this.SFUniqueNumber__c = sFUniqueNumber__c;
    }

    public String getStatus__c() {
        return Status__c;
    }

    public void setStatus__c(String status__c) {
        this.Status__c = status__c;
    }

    public String getUnit__c() {
        return Unit__c;
    }

    public void setUnit__c(String unit__c) {
        this.Unit__c = unit__c;
    }

    public String getRecord_Id__c() {
        return Record_Id__c;
    }

    public void setRecord_Id__c(String record_Id__c) {
        this.Record_Id__c = record_Id__c;
    }

	public String getLastModifiedDate() {
		return LastModifiedDate;
	}

	public void setLastModifiedDate(String lastModifiedDate) {
		LastModifiedDate = lastModifiedDate;
	}
    
    
}
