package com.citidev.services;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.*;
import java.util.stream.Collectors;

import org.adempiere.exceptions.AdempiereException;
import org.compiere.model.MPayment;
import org.compiere.model.Query;
import org.compiere.util.Env;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.citidev.client.impl.ReceiptApi;
import com.citidev.dto.ReceiptDTO;

public class ReceiptService {

	private static final Logger log = LoggerFactory.getLogger(ReceiptService.class);
    private final ReceiptApi receiptApi;

    public ReceiptService() {
        this.receiptApi = new ReceiptApi();
    }

    public List<ReceiptDTO> getAllReceipts() {
        return receiptApi.getAllReceipts();
    }

    public ReceiptDTO getReceiptById(String id) {
        return receiptApi.getReceiptById(id);
    }

    public ReceiptDTO createReceipt(ReceiptDTO dto) {
    	
        return receiptApi.createReceipt(dto);

    }

    public void updateReceipt(String id, ReceiptDTO dto) {
        receiptApi.updateReceipt(id, dto);
    }

    public boolean deleteReceipt(String id) {
        return receiptApi.deleteReceipt(id);
    }

    public int syncReceiptsFromSalesforce() {
        List<ReceiptDTO> dtos = getAllReceipts();

        if (dtos == null || dtos.isEmpty()) {
            log.warn("No receipts found in Salesforce.");
            return 0;
        }

        log.info("Starting Salesforce, ERP receipt sync...");

        Map<String, MPayment> existing = fetchExistingPayments(
                dtos.stream().map(ReceiptDTO::getId).collect(Collectors.toList())
        );

        int syncedCount = 0;

        for (ReceiptDTO dto : dtos) {
            MPayment payment = existing.get(dto.getId());

            if (payment == null) {
                payment = new MPayment(Env.getCtx(), 0, null);
            } else if (payment.isProcessed()) {
                log.warn("Skipping processed payment: " + dto.getName());
                continue;
            }

            populatePayment(payment, dto);
            try {
                payment.saveEx();
                syncedCount++;
            } catch (Exception e) {
                log.error("Failed to save payment for: " + dto.getName() + " | " + e.getMessage());
            }
        }

        log.info("Receipts synchronized successfully: " + syncedCount);
        return syncedCount;
    }
    
    public int syncReceiptsToSalesforce() {
        List<MPayment> payments = new Query(Env.getCtx(), MPayment.Table_Name, "SF_UID IS NULL AND IsActive='Y'", null)
                .list();

        if (payments == null || payments.isEmpty()) {
            log.info("No new payments found to sync to Salesforce.");
            return 0;
        }

        int syncedCount = 0;

        for (MPayment payment : payments) {
            try {
                // Convert MPayment to DTO
                ReceiptDTO dto = toReceiptDTO(payment);

                // Send to Salesforce
                ReceiptDTO response = receiptApi.createReceipt(dto);

                // Save returned SF ID
                if (response != null && response.getId() != null) {
                    payment.set_ValueOfColumn("SF_UID", response.getId());
                    payment.saveEx();
                    syncedCount++;
                    log.info("Synced Payment [" + payment.getDocumentNo() + "] with SF_UID: " + response.getId());
                }

            } catch (Exception e) {
                log.error("Failed to sync payment: " + payment.getDocumentNo() + " | " + e.getMessage());
            }
        }

        log.info("Payments synced to Salesforce: " + syncedCount);
        return syncedCount;
    }
    
//    private ReceiptDTO toReceiptDTO(MPayment payment) {
//        ReceiptDTO dto = new ReceiptDTO();
//
//        dto.setName(payment.getDocumentNo());
//        dto.setAmount__c(payment.getPayAmt().toPlainString());
//
//        dto.setAccount__c(getSFAccountIdByBP(payment.getC_BPartner_ID()));
//
//        Integer projectId = (Integer) payment.get_Value("C_Project_ID");
//        dto.setProject__c(projectId != null ? projectId.toString() : null);
//
//        dto.setUnit__c(null);
//
//        dto.setOpportunity__c(null);
//
//        dto.setStatus__c(payment.getDocStatus());
//
//        dto.setPayment_Method__c(payment.getTenderType());
//
//        Integer bankId = (Integer) payment.get_Value("C_BankAccount_ID");
//        dto.setBank__c(bankId != null ? bankId.toString() : null);
//        
//        dto.setAutogenerated__c(false);
//
//        
//        return dto;
//    }
    
    private ReceiptDTO toReceiptDTO(MPayment payment) {
        ReceiptDTO dto = new ReceiptDTO();

//        dto.setName(payment.getDocumentNo());
        dto.setAmount__c(payment.getPayAmt().toPlainString());
        dto.setAccount__c(getSFAccountIdByBP(payment.getC_BPartner_ID()));

        Integer projectId = (Integer) payment.get_Value("C_Project_ID");
        dto.setProject__c(projectId != null ? projectId.toString() : null);

        dto.setUnit__c(null);
        dto.setOpportunity__c(null);
        dto.setStatus__c(null);
        dto.setPayment_Method__c("Cash");
//        dto.setSFUniqueNumber__c(payment.getDocumentNo()); 


        Integer bankId = (Integer) payment.get_Value("C_BankAccount_ID");
        dto.setBank__c(bankId != null ? bankId.toString() : null);

        if (dto.getBank__c() != null && dto.getBank__c().matches("\\d+")) {
            dto.setBank__c(null);
        }
        if (dto.getStatus__c() != null && dto.getStatus__c().matches("\\d+")) {
            dto.setStatus__c(null);
        }
        if (dto.getPayment_Method__c() != null && dto.getPayment_Method__c().matches("\\d+")) {
            dto.setPayment_Method__c(null);
        }

        dto.setAutogenerated__c(false);

        return dto;
    }


    private Map<String, MPayment> fetchExistingPayments(List<String> sfIds) {
        Map<String, MPayment> data = new HashMap<>();
        if (sfIds == null || sfIds.isEmpty())
            return data;

        String placeholders = sfIds.stream().map(i -> "?").collect(Collectors.joining(","));
        String where = "SF_UID IN (" + placeholders + ")";
        List<MPayment> objects = new Query(Env.getCtx(), MPayment.Table_Name, where, null)
                .setParameters(sfIds.toArray())
                .list();

        for (MPayment p : objects) {
                data.put((String)p.get_Value("SF_UID"), p);
        }
        return data;
    }

    private void populatePayment(MPayment payment, ReceiptDTO dto) {
        int orgId = Env.getAD_Org_ID(Env.getCtx());
        payment.setAD_Org_ID(orgId);

        int bankId = new Query(Env.getCtx(), "C_BankAccount", "AD_Org_ID=?", null)
                .setParameters(orgId)
                .firstId();
        if (bankId <= 0)
            throw new AdempiereException("No Bank Account found for current Org");

        payment.setC_BankAccount_ID(bankId);

        payment.set_ValueOfColumn("SF_UID", dto.getId());
        payment.setDocumentNo(dto.getName());
        payment.setDescription("Imported from Salesforce");
        payment.setC_Currency_ID(304);
        Timestamp now = new Timestamp(System.currentTimeMillis());
        payment.setDateTrx(now);
        payment.setDateAcct(now);
        payment.setIsReceipt(true);
        payment.setTenderType(MPayment.TENDERTYPE_Cash);

        if (dto.getAccount__c() != null) {
            int bpId = getBPartnerIdBySFUID(dto.getAccount__c());
            if (bpId > 0) {
                payment.setC_BPartner_ID(bpId);
            } else {
                log.warn("No BPartner found for Account ID: " + dto.getAccount__c());
            }
        }

        try {
            BigDecimal amt = (dto.getAmount__c() != null)
            ? new BigDecimal(dto.getAmount__c())
            		: BigDecimal.ZERO;
            
            payment.setPayAmt(amt);
        } catch (Exception e) {
            payment.setPayAmt(BigDecimal.ZERO);
        }

        payment.set_ValueOfColumn("ProjectSF", dto.getProject__c());
        payment.set_ValueOfColumn("UnitSF", dto.getUnit__c());
        payment.set_ValueOfColumn("OpportunitySF", dto.getOpportunity__c());
        payment.set_ValueOfColumn("StatusSF", dto.getStatus__c());
        payment.set_ValueOfColumn("PaymentMethodSF", dto.getPayment_Method__c());
        payment.set_ValueOfColumn("BankSF", dto.getBank__c());
    }

    /** 🔹 Get BPartner by Salesforce UID */
    private int getBPartnerIdBySFUID(String sfAccountId) {
        if (sfAccountId == null)
            return 0;
        return new Query(Env.getCtx(), "C_BPartner", "SF_UID=?", null)
                .setParameters(sfAccountId)
                .firstId();
    }
    
    private String getSFAccountIdByBP(int bpId) {
        if (bpId <= 0)
            return null;
        return new Query(Env.getCtx(), "C_BPartner", "C_BPartner_ID=?", null)
                .setParameters(bpId)
                .first()
                .get_ValueAsString("SF_UID");
    }

}