package com.citidev.client.impl;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.citidev.client.api.ApiClientProvider;
import com.citidev.client.api.IApiClient;
import com.citidev.client.api.IReceiptApi;
import com.citidev.client.api.SalesforceEndpoints;
import com.citidev.dto.ReceiptDTO;
import com.citidev.services.PropertyUnitService;
import com.citidev.utilities.JsonUtils;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

public class ReceiptApi implements IReceiptApi{
	
	private final IApiClient apiClient;
	private static final Logger log = LoggerFactory.getLogger(PropertyUnitService.class);
    private static final String OBJECT_NAME = "Receipt__c";
    private static final String STANDARD_SELECT = String.join(" ",
            "SELECT Id, Name, Account__c, Amount__c, Autogenerated__c, Bank__c, CustomerBank__c,"
            + " DueDate__c, Opportunity__c, PaymentReference__c, PaymentStatus__c,"
            + " Payment_Method__c, Payment__c, Project__c, ReceiptDate__c, SFUniqueNumber__c,"
            + " Status__c, Unit__c, Record_Id__c FROM", OBJECT_NAME
    );
    
    public ReceiptApi() {
        this.apiClient = ApiClientProvider.getApiClient();
    }

	@Override
	public List<ReceiptDTO> getAllReceipts() {
		String query = buildSoqlQuery("");
        String url = SalesforceEndpoints.QUERY.getUrl(encode(query));
        String response = apiClient.queryAll(url);
        return JsonUtils.extractStandrdSFObjects(response, ReceiptDTO.class);
	}

	@Override
	public ReceiptDTO getReceiptById(String id) {
		String url = SalesforceEndpoints.OBJECT_BY_ID.getUrl(OBJECT_NAME, id);
        String response = apiClient.get(url);
        return JsonUtils.fromJson(response, ReceiptDTO.class);
	}

	@Override
	public void updateReceipt(String id, Map<String, Object> data) {
		String url = SalesforceEndpoints.UPDATE_OBJECT.getUrl(OBJECT_NAME, id);
        String body = JsonUtils.toJson(data);
        apiClient.patch(url, body);
		
	}
	
//	@Override
//	public ReceiptDTO createReceipt(ReceiptDTO dto) {
//		String url = SalesforceEndpoints.CREATE_OBJECT.getUrl(OBJECT_NAME);
//        String body = JsonUtils.toJson(dto);
//        String response = apiClient.post(url, body);
//        return JsonUtils.fromJson(response, ReceiptDTO.class);
//	}
	
	@Override
	public ReceiptDTO createReceipt(ReceiptDTO dto) {
	    String url = SalesforceEndpoints.CREATE_OBJECT.getUrl(OBJECT_NAME);

	    Map<String, Object> payload = new HashMap<>();
	    if (dto.getAmount__c() != null) payload.put("Amount__c", dto.getAmount__c());
	    if (dto.getAccount__c() != null) payload.put("Account__c", dto.getAccount__c());
	    if (dto.getProject__c() != null) payload.put("Project__c", dto.getProject__c());
	    if (dto.getUnit__c() != null) payload.put("Unit__c", dto.getUnit__c());
	    if (dto.getOpportunity__c() != null) payload.put("Opportunity__c", dto.getOpportunity__c());
	    if (dto.getPayment_Method__c() != null) payload.put("Payment_Method__c", dto.getPayment_Method__c());
	    if (dto.getBank__c() != null) payload.put("Bank__c", dto.getBank__c());
	    if (dto.getStatus__c() != null) payload.put("Status__c", dto.getStatus__c());

	    String body = JsonUtils.toJson(payload);

	    log.info("[DEBUG] Sending POST to Salesforce URL: {}", url);
	    log.info("[DEBUG] Request Body: {}", body);

	    try {
	        String response = apiClient.post(url, body);
	        log.info("[DEBUG] Salesforce Response: {}", response);

	        ReceiptDTO created = JsonUtils.fromJson(response, ReceiptDTO.class);

	        JsonNode node = new ObjectMapper().readTree(response);
	        if (node.has("id") && (created.getId() == null || created.getId().isEmpty())) {
	            created.setId(node.get("id").asText());
	        }

	        return created;

	    } catch (Exception e) {
	        log.error("[ERROR] Salesforce POST failed for URL {}: {}", url, e.getMessage(), e);
	        return null;
	    }
	}





	
	@Override
	public ReceiptDTO updateReceipt(String id, ReceiptDTO dto) {
		 String url = SalesforceEndpoints.UPDATE_OBJECT.getUrl(OBJECT_NAME, id);
	        String body = JsonUtils.toJson(dto);
	        apiClient.patch(url, body);
	        return dto;
		
	}
	
	@Override
	public boolean deleteReceipt(String id) {
		 String url = SalesforceEndpoints.DELETE_OBJECT.getUrl(OBJECT_NAME, id);
	        apiClient.delete(url);
	        return true;
	}
	
	// Helper Methods
    private String buildSoqlQuery(String filter) {
        return STANDARD_SELECT + (filter == null ? "" : filter);
    }

    private String encode(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }

}
